apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
        - args:
            - --cookie-secure=false
            - --upstream=file://dev/null
            - --http-address=0.0.0.0:4180
            - --cookie-secret=changeme
            - --client-id=changeme
            - --client-secret=changeme
            - --email-domain="*"

            - --provider=oidc
            - --provider-display-name="Dex oidc"
            - --redirect-url=http://10.106.200.144:4180/oauth2/callback
            #following should match what is configured in dex
            - --oidc-issuer-url=http://192.168.64.1:5556/dex

            #- --pass-access-token=true
            #- --pass-authorization-header=true
            #- --set-authorization-header=true
            #- --oidc-issuer-url=https://auth.justin-tech.com/auth/realms/Justin-Tech
            #- --login-url=https://auth.justin-tech.com/auth/realms/Justin-Tech/protocol/openid-connect/auth
            #- --redeem-url=https://auth.justin-tech.com/auth/realms/Justin-Tech/protocol/openid-connect/token
            #- --validate-url=https://auth.justin-tech.com/auth/realms/Justin-Tech/protocol/openid-connect/userinfo
            #- --http-address=0.0.0.0:4180
            #- --cookie-expire=4h0m0s
            #- --whitelist-domain=".corp.justin-tech.com"
            #- --cookie-domain=.justin-tech.com
            - --standard-logging=true
            - --auth-logging=true
            - --request-logging=true
            #- --skip-provider-button=true
            #- --upstream=static://
            #- --redis-connection-url=redis://redis-master.default.svc.cluster.local:6379
            #- --session-store-type=redis
          image: quay.io/pusher/oauth2_proxy:v5.1.1
          #image: quay.io/pusher/oauth2_proxy:latest
          imagePullPolicy: Always
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauthproxy-service
  namespace: default
spec:
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180
  selector:
    k8s-app: oauth2-proxy